export declare const regexScalar: RegExp;
export declare const regexFloat: RegExp;
export declare const regexInteger: RegExp;
export declare function isWhitespace(char: string): boolean;
export declare function isQuoted(text: string): boolean;
export declare function stripQuotes(text: string): string;
declare function isMatchingValue(str: string, regex: RegExp): boolean;
export declare function isFloatValue(n: string): boolean;
export declare function isIntegerValue(n: string): boolean;
export declare function isScalarValue(n: string): boolean;
declare const _default: {
    isWhitespace: typeof isWhitespace;
    isQuoted: typeof isQuoted;
    stripQuotes: typeof stripQuotes;
    isMatchingValue: typeof isMatchingValue;
    isFloatValue: typeof isFloatValue;
    isIntegerValue: typeof isIntegerValue;
    isScalarValue: typeof isScalarValue;
};
export default _default;
