name: Deploy package "KV" to NPM

on:
  workflow_dispatch:
  push:
    tags:
      - 'kv-[0-9].[0-9].[0-9]'

jobs:
  deploy_kv:
    uses: ./.github/workflows/_deploy.yml
    with:
      package-name: kv
    secrets: inherit